# ===================================================================
# keycloak specific properties
# ===================================================================
keycloak:
  auth-server-url: https://localhost:18443/auth
  realm: sso
  resource: product-app
  public-client: true